apiVersion: v1
kind: Service
metadata:
  name: roscore
spec:
  selector:
    func: ros-core
  ports:
    - port: 11311
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-core-pub
spec:
  replicas: 1
  selector:
    matchLabels:
      func: ros-core
  template:
    metadata:
      labels:
        func: ros-core
    spec:
      hostname: roscore
      containers:
      - name: core
        image: ros:pubsub
        imagePullPolicy: Never
        ports:
        - containerPort: 11311
        env:
        - name: ROS_MASTER_URI
          value: http://roscore:11311/
        command:
        - /bin/bash
        - -c
        - "source /opt/ros/devel/setup.bash && roscore"
      - name: pub
        image: ros:pubsub
        imagePullPolicy: Never
        command:
        - /bin/bash
        - -c
        - 'sleep 10 && source /opt/ros/devel/setup.bash && rosrun roscpp_tutorials talker'
